/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import visao.UICadCliente;
import visao.UICadFuncionario;
import visao.UICadMovel;
import visao.UIManutencaoCliente;
import visao.UIManutencaoFuncionario;
import visao.UIManutencaoMovel;

/**
 *
 * @author vinicius
 */
public class MenuPrincipal extends javax.swing.JFrame implements InternalFrameListener{

    private boolean flagUICadCliente = false;
    private boolean flagUICadFuncionario = false;
    private boolean flagUICadMovel = false;
    private boolean flagUIManutencaoCliente = false;
    private boolean flagUIManutencaoFuncionario = false;
    private boolean flagUIManutencaoMovel = false;
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JDesktopPane();
        jmbMenuPrincipal = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCadastrarMoveis = new javax.swing.JMenuItem();
        jmiCadastrarFuncionario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiManutencaoMoveis = new javax.swing.JMenuItem();
        jmiManutencaoFuncionarios = new javax.swing.JMenuItem();
        jmiManutencaoClientes = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        javax.swing.GroupLayout jAreaTrabalhoLayout = new javax.swing.GroupLayout(jAreaTrabalho);
        jAreaTrabalho.setLayout(jAreaTrabalhoLayout);
        jAreaTrabalhoLayout.setHorizontalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        jAreaTrabalhoLayout.setVerticalGroup(
            jAreaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jmCadastro.setText("Cadastros");

        jmiCadastrarMoveis.setText("Cadastro de Moveis");
        jmiCadastrarMoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarMoveisActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadastrarMoveis);

        jmiCadastrarFuncionario.setText("Cadastro de Funcionarios");
        jmiCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCadastrarFuncionario);

        jMenuItem1.setText("Cadastro de Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmCadastro.add(jMenuItem1);

        jmbMenuPrincipal.add(jmCadastro);

        jmManutencao.setText("Manutenções");

        jmiManutencaoMoveis.setText("Manutenção Moveis ");
        jmiManutencaoMoveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManutencaoMoveisActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManutencaoMoveis);

        jmiManutencaoFuncionarios.setText("Manutenção Funcionarios");
        jmiManutencaoFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManutencaoFuncionariosActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManutencaoFuncionarios);

        jmiManutencaoClientes.setText("Manutenção Clientes");
        jmiManutencaoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManutencaoClientesActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManutencaoClientes);

        jmbMenuPrincipal.add(jmManutencao);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jmbMenuPrincipal.add(jmSair);

        setJMenuBar(jmbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void abrirCadMovel(){
        if (!flagUICadMovel) {
            UICadMovel ucm =  new UICadMovel();
            jAreaTrabalho.add(ucm);
            ucm.setVisible(true);
            flagUICadMovel = true;
            ucm.addInternalFrameListener(this);
        }
    }
    
    private void abrirCadFuncionario(){
        if (!flagUICadFuncionario) {
            UICadFuncionario ucf =  new UICadFuncionario();
            jAreaTrabalho.add(ucf);
            ucf.setVisible(true);
            flagUICadFuncionario = true;
            ucf.addInternalFrameListener(this);
        }
    }
    
    private void abrirCadCliente(){
        if (!flagUICadCliente) {
            UICadCliente ucc =  new UICadCliente();
            jAreaTrabalho.add(ucc);
            ucc.setVisible(true);
            flagUICadCliente = true;
            ucc.addInternalFrameListener(this);
        }
    }
    
    private void abrirManMovel(){
        if (!flagUIManutencaoMovel) {
            UIManutencaoMovel umm = new UIManutencaoMovel();
            jAreaTrabalho.add(umm);
            umm.setVisible(true);
            flagUIManutencaoMovel = true;
            umm.addInternalFrameListener(this);
        }
    }
    
    private void abrirManCliente(){
        if (!flagUIManutencaoCliente) {
            UIManutencaoCliente umc = new UIManutencaoCliente();
            jAreaTrabalho.add(umc);
            umc.setVisible(true);
            flagUIManutencaoCliente = true;
            umc.addInternalFrameListener(this);
        }
    }
    private void abrirManFuncionario(){
        
        if (!flagUIManutencaoFuncionario) {
            UIManutencaoFuncionario umf = new UIManutencaoFuncionario();
            jAreaTrabalho.add(umf);
            umf.setVisible(true);
            flagUIManutencaoFuncionario = true;
            umf.addInternalFrameListener(this);
        }
    }
    
    
    
    private void jmiCadastrarMoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarMoveisActionPerformed
        abrirCadMovel();
    }//GEN-LAST:event_jmiCadastrarMoveisActionPerformed

    private void jmiManutencaoMoveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManutencaoMoveisActionPerformed
        abrirManMovel();
    }//GEN-LAST:event_jmiManutencaoMoveisActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jmSairMouseClicked

    private void jmiCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarFuncionarioActionPerformed
        
        abrirCadFuncionario();
        
    }//GEN-LAST:event_jmiCadastrarFuncionarioActionPerformed

    private void jmiManutencaoFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManutencaoFuncionariosActionPerformed
        
        
        abrirManFuncionario();
    }//GEN-LAST:event_jmiManutencaoFuncionariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        abrirCadCliente();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmiManutencaoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManutencaoClientesActionPerformed
        abrirManCliente();
    }//GEN-LAST:event_jmiManutencaoClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
            com.jtattoo.plaf.acryl.AcrylLookAndFeel.setTheme("Green", "INSERT YOUR LICENSE KEY HERE", "my company");
        UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuBar jmbMenuPrincipal;
    private javax.swing.JMenuItem jmiCadastrarFuncionario;
    private javax.swing.JMenuItem jmiCadastrarMoveis;
    private javax.swing.JMenuItem jmiManutencaoClientes;
    private javax.swing.JMenuItem jmiManutencaoFuncionarios;
    private javax.swing.JMenuItem jmiManutencaoMoveis;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        if (ife.getInternalFrame() instanceof UICadCliente) {
            flagUICadCliente = false;
        } else if(ife.getInternalFrame() instanceof UICadFuncionario) {
            flagUICadFuncionario = false;
        } else if(ife.getInternalFrame() instanceof UICadMovel){
            flagUICadMovel = false;
        } else if(ife.getInternalFrame() instanceof UIManutencaoCliente){
            flagUIManutencaoCliente = false;
        } else if(ife.getInternalFrame() instanceof UIManutencaoFuncionario){
            flagUIManutencaoFuncionario = false;
        } else if(ife.getInternalFrame() instanceof UIManutencaoMovel){
            flagUIManutencaoMovel = false;
        }
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {
        
    }
}
