/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Funcionario;
import servicos.FuncionarioServicos;

/**
 *
 * @author vinicius
 */
public class UICadFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form UICadFuncionario
     */
    public UICadFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSetor = new javax.swing.ButtonGroup();
        bgEstadoCivil = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlCpf = new javax.swing.JLabel();
        jtCpf = new javax.swing.JTextField();
        jlSetor = new javax.swing.JLabel();
        jrVendas = new javax.swing.JRadioButton();
        jrMontagem = new javax.swing.JRadioButton();
        jrMarketing = new javax.swing.JRadioButton();
        jlRg = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jlEndereco = new javax.swing.JLabel();
        jtRg = new javax.swing.JTextField();
        jtTelefone = new javax.swing.JTextField();
        jtEndereco = new javax.swing.JTextField();
        jlNomeErro = new javax.swing.JLabel();
        jlCpfErro = new javax.swing.JLabel();
        jlRgErro = new javax.swing.JLabel();
        jlTelefoneErro = new javax.swing.JLabel();
        jlEnderecoErro = new javax.swing.JLabel();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Funcionarios");

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome:");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jlCpf.setText("Cpf:");

        jtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCpfFocusLost(evt);
            }
        });
        jtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCpfKeyPressed(evt);
            }
        });

        jlSetor.setText("Setor");

        bgSetor.add(jrVendas);
        jrVendas.setText("Vendas");
        jrVendas.setActionCommand("Vendas");
        jrVendas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrVendasKeyPressed(evt);
            }
        });

        bgSetor.add(jrMontagem);
        jrMontagem.setText("Montagem");
        jrMontagem.setActionCommand("Montagem");
        jrMontagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrMontagemKeyPressed(evt);
            }
        });

        bgSetor.add(jrMarketing);
        jrMarketing.setText("Marketing");
        jrMarketing.setActionCommand("Marketing");
        jrMarketing.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrMarketingKeyPressed(evt);
            }
        });

        jlRg.setText("RG:");

        jlTelefone.setText("Telefone:");

        jlEndereco.setText("Endereço:");

        jtRg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtRgFocusLost(evt);
            }
        });
        jtRg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtRgKeyPressed(evt);
            }
        });

        jtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTelefoneFocusLost(evt);
            }
        });
        jtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTelefoneKeyPressed(evt);
            }
        });

        jtEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtEnderecoFocusLost(evt);
            }
        });
        jtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtEnderecoKeyPressed(evt);
            }
        });

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlSetor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrVendas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrMontagem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrMarketing, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlRg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtRg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCpfErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlRgErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTelefoneErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlEnderecoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNome)
                    .addComponent(jlCpf)
                    .addComponent(jlSetor)
                    .addComponent(jlRg)
                    .addComponent(jlEndereco, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlTelefone))
                .addGap(47, 47, 47)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtNome)
                    .addComponent(jtCpf)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jrVendas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrMontagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jrMarketing))
                    .addComponent(jtEndereco)
                    .addComponent(jtTelefone)
                    .addComponent(jtRg))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlNomeErro, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jlCpfErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlEnderecoErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlRgErro, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jlTelefoneErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlNome)
                        .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlCpfErro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtCpf, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSetor)
                    .addComponent(jrVendas)
                    .addComponent(jrMontagem)
                    .addComponent(jrMarketing))
                .addGap(19, 19, 19)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlRg)
                    .addComponent(jlRgErro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtRg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEndereco)))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlTelefoneErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlEnderecoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpAcoesLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpDados)
            .addComponent(jlpAcoes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Funcionario fVO = new Funcionario();
    
    private void cadastrar() {
        try {
            if (!jtNome.getText().isEmpty()) {
                fVO.setNome(jtNome.getText());
            } else {
                throw new NumberFormatException("Nome em Branco!");
            }
            if (!jtCpf.getText().isEmpty()) {
                fVO.setCpf(jtCpf.getText());
            } else {
                throw new NumberFormatException("Cpf em Branco!");
            }
            if (!jtRg.getText().isEmpty()) {
                fVO.setRg(jtRg.getText());
            } else {
                throw new NumberFormatException("Rg em Branco!");
            }
            if (!jtEndereco.getText().isEmpty()) {
                fVO.setEndereco(jtEndereco.getText());
            } else {
                throw new NumberFormatException("Endereço em Branco!");
            }
            if (!jtTelefone.getText().isEmpty()) {
                fVO.setTelefone(Integer.parseInt(jtTelefone.getText()));
            } else {
                throw new NumberFormatException("Telefone em Branco!");
            }
            if (!jrVendas.isSelected() && jrMontagem.isSelected() && jrMarketing.isSelected()) {
                throw new Exception("Selecione um tipo!");
            } else {
                fVO.setSetor(bgSetor.getSelection().getActionCommand());
            }
            
            FuncionarioServicos fs = servicos.ServicosFactory.getFuncionarioServicos();
            
            fs.cadastrarFuncionario(fVO);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Funcionario cadastrado com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage(),
                    "erro",
                    JOptionPane.ERROR_MESSAGE);
        }//fecha catch
        jtNome.grabFocus();
    }//fecha método cadastrar
        private void limpar(){
            jtNome.setText(null);
            jtCpf.setText(null);
            bgSetor.clearSelection();
            jtRg.setText(null);
            jtTelefone.setText(null);
            jtEndereco.setText(null);
        }
    
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCpf.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCpfKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrVendas.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtCpfKeyPressed

    private void jrVendasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrVendasKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrMontagem.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrVendasKeyPressed

    private void jrMontagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMontagemKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrMarketing.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrMontagemKeyPressed

    private void jrMarketingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrMarketingKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtRg.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrMarketingKeyPressed

    private void jtRgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtRgKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtTelefone.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtRgKeyPressed

    private void jtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelefoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtEndereco.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtTelefoneKeyPressed

    private void jtEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEnderecoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCadastrar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtEnderecoKeyPressed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        // TODO add your handling code here:
        if (jtNome.getText().isEmpty()) {
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtNome.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtNome.getText().isEmpty()){
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCpfFocusLost
        // TODO add your handling code here:
        if (jtCpf.getText().isEmpty()) {
            jtCpf.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtCpf.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtCpf.getText().isEmpty()){
            jlCpfErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlCpfErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtCpfFocusLost

    private void jtRgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtRgFocusLost
        // TODO add your handling code here:
        if (jtRg.getText().isEmpty()) {
            jtRg.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtRg.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtRg.getText().isEmpty()){
            jlRgErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlRgErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtRgFocusLost

    private void jtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTelefoneFocusLost
        // TODO add your handling code here:
        if (jtTelefone.getText().isEmpty()) {
            jtTelefone.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtTelefone.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtNome.getText().isEmpty()){
            jlTelefoneErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlTelefoneErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtTelefoneFocusLost

    private void jtEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEnderecoFocusLost
        // TODO add your handling code here:
        if (jtEndereco.getText().isEmpty()) {
            jtEndereco.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtEndereco.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtEndereco.getText().isEmpty()){
            jlEnderecoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlEnderecoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtEnderecoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEstadoCivil;
    private javax.swing.ButtonGroup bgSetor;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlCpfErro;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlEnderecoErro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlRg;
    private javax.swing.JLabel jlRgErro;
    private javax.swing.JLabel jlSetor;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLabel jlTelefoneErro;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JRadioButton jrMarketing;
    private javax.swing.JRadioButton jrMontagem;
    private javax.swing.JRadioButton jrVendas;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JTextField jtEndereco;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtRg;
    private javax.swing.JTextField jtTelefone;
    // End of variables declaration//GEN-END:variables
}
