/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Movel;
import servicos.MovelServicos;

/**
 *
 * @author vinicius
 */
public class UICadMovel extends javax.swing.JInternalFrame {

    /**
     * Creates new form UICadMoveis
     */
    public UICadMovel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipo = new javax.swing.ButtonGroup();
        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jlPreco = new javax.swing.JLabel();
        jlTipo = new javax.swing.JLabel();
        jlQuantidade = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jtPreco = new javax.swing.JTextField();
        jrQuarto = new javax.swing.JRadioButton();
        jrSala = new javax.swing.JRadioButton();
        jrCozinha = new javax.swing.JRadioButton();
        jtQuantidade = new javax.swing.JTextField();
        jlAltura = new javax.swing.JLabel();
        jlLargura = new javax.swing.JLabel();
        jlComprimento = new javax.swing.JLabel();
        jtAltura = new javax.swing.JTextField();
        jtLargura = new javax.swing.JTextField();
        jtComprimento = new javax.swing.JTextField();
        jlNomeErro = new javax.swing.JLabel();
        jlPrecoErro = new javax.swing.JLabel();
        jlQuantidadeErro = new javax.swing.JLabel();
        jlAlturaErro = new javax.swing.JLabel();
        jlLarguraErro = new javax.swing.JLabel();
        jlComprimentoErro = new javax.swing.JLabel();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Moveis");

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome: ");

        jlPreco.setText("Preço:");

        jlTipo.setText("Tipo:");

        jlQuantidade.setText("Quantidade:");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jtPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPrecoFocusLost(evt);
            }
        });
        jtPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPrecoKeyPressed(evt);
            }
        });

        bgTipo.add(jrQuarto);
        jrQuarto.setText("Quarto");
        jrQuarto.setActionCommand("Quarto");
        jrQuarto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrQuartoKeyPressed(evt);
            }
        });

        bgTipo.add(jrSala);
        jrSala.setText("Sala");
        jrSala.setActionCommand("Sala");
        jrSala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrSalaKeyPressed(evt);
            }
        });

        bgTipo.add(jrCozinha);
        jrCozinha.setText("Cozinha");
        jrCozinha.setActionCommand("Cozinha");
        jrCozinha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jrCozinhaKeyPressed(evt);
            }
        });

        jtQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtQuantidadeFocusLost(evt);
            }
        });
        jtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtQuantidadeKeyPressed(evt);
            }
        });

        jlAltura.setText("Altura:");

        jlLargura.setText("Largura:");

        jlComprimento.setText("Comprimento:");

        jtAltura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtAlturaFocusLost(evt);
            }
        });
        jtAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtAlturaKeyPressed(evt);
            }
        });

        jtLargura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtLarguraFocusLost(evt);
            }
        });
        jtLargura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtLarguraKeyPressed(evt);
            }
        });

        jtComprimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtComprimentoFocusLost(evt);
            }
        });
        jtComprimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtComprimentoKeyPressed(evt);
            }
        });

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlQuantidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrQuarto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrSala, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jrCozinha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtQuantidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlAltura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlLargura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlComprimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtAltura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtLargura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtComprimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlPrecoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlQuantidadeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlAlturaErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlLarguraErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlComprimentoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPreco)
                    .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTipo)
                    .addComponent(jlQuantidade)
                    .addComponent(jlAltura)
                    .addComponent(jlComprimento)
                    .addComponent(jlLargura))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addComponent(jrQuarto)
                        .addGap(18, 18, 18)
                        .addComponent(jrSala)
                        .addGap(18, 18, 18)
                        .addComponent(jrCozinha))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jlpDadosLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jtComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlNomeErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlComprimentoErro, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(jlAlturaErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlLarguraErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlQuantidadeErro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPrecoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPreco)))
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jlPrecoErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipo)
                    .addComponent(jrQuarto)
                    .addComponent(jrSala)
                    .addComponent(jrCozinha))
                .addGap(19, 19, 19)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQuantidade)
                    .addComponent(jlQuantidadeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                        .addComponent(jlAltura)
                        .addGap(8, 8, 8))
                    .addComponent(jtAltura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAlturaErro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlLargura)
                    .addComponent(jlLarguraErro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlComprimentoErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlComprimento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtComprimento, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpDados)
            .addComponent(jlpAcoes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlpDados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        Movel mVO = new Movel();
        
        private void cadastrar() {
        try {
            if (!jtNome.getText().isEmpty()) {
                mVO.setNome(jtNome.getText());
            } else {
                throw new NumberFormatException("Nome em Branco!");
            }
            
            if (!jrQuarto.isSelected() && jrSala.isSelected() && jrCozinha.isSelected()) {
                throw new Exception("Selecione um tipo!");
            } else {
                mVO.setTipo(bgTipo.getSelection().getActionCommand());
            }
            
            if (!jtPreco.getText().isEmpty()) {
                mVO.setPreco(Double.parseDouble(jtPreco.getText()));
            } else {
                throw new NumberFormatException("Preço em Branco!");
            }
            
            if (!jtQuantidade.getText().isEmpty()) {
                mVO.setQuantidade(Integer.parseInt(jtQuantidade.getText()));
            } else {
                throw new NumberFormatException("Quantidade em Branco!");
            }
            
            if (!jtAltura.getText().isEmpty()) {
                mVO.setAltura(Double.parseDouble(jtAltura.getText()));
            } else {
                throw new NumberFormatException("Altura em Branco!");
            }
            
            if (!jtLargura.getText().isEmpty()) {
                mVO.setLargura(Double.parseDouble(jtLargura.getText()));
            } else {
                throw new NumberFormatException("Largura em Branco!");
            }
            
            if (!jtComprimento.getText().isEmpty()) {
                mVO.setComprimento(Double.parseDouble(jtComprimento.getText()));
            } else {
                throw new NumberFormatException("Comprimento em Branco!");
            }
            
            
            MovelServicos ms = servicos.ServicosFactory.getMovelServicos();
            ms.cadastrarMovel(mVO);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Produto cadastrado com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Erro! "+e.getMessage(),
                    "erro",
                    JOptionPane.ERROR_MESSAGE);
        }//fecha catch
        
    }//fecha método cadastrar
        private void limpar(){
            jtNome.setText(null);
            jtPreco.setText(null);
            jtQuantidade.setText(null);
            bgTipo.clearSelection();
            jtLargura.setText(null);
            jtAltura.setText(null);
            jtComprimento.setText(null);
        }
    
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtPreco.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtPrecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrQuarto.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtPrecoKeyPressed

    private void jrQuartoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrQuartoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrSala.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrQuartoKeyPressed

    private void jrSalaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrSalaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jrCozinha.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrSalaKeyPressed

    private void jrCozinhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrCozinhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtQuantidade.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jrCozinhaKeyPressed

    private void jtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtQuantidadeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtAltura.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtQuantidadeKeyPressed

    private void jtAlturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtAlturaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtLargura.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtAlturaKeyPressed

    private void jtLarguraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtLarguraKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtComprimento.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtLarguraKeyPressed

    private void jtComprimentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtComprimentoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCadastrar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtComprimentoKeyPressed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        // TODO add your handling code here:
        if (jtNome.getText().isEmpty()) {
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtNome.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtNome.getText().isEmpty()){
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPrecoFocusLost
        // TODO add your handling code here:
        if (jtPreco.getText().isEmpty()) {
            jtPreco.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtPreco.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtPreco.getText().isEmpty()){
            jlPrecoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlPrecoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtPrecoFocusLost

    private void jtQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtQuantidadeFocusLost
        // TODO add your handling code here:
        if (jtQuantidade.getText().isEmpty()) {
            jtQuantidade.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtQuantidade.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtQuantidade.getText().isEmpty()){
            jlQuantidadeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlQuantidadeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtQuantidadeFocusLost

    private void jtAlturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtAlturaFocusLost
        // TODO add your handling code here:
        if (jtAltura.getText().isEmpty()) {
            jtAltura.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtAltura.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtAltura.getText().isEmpty()){
            jlAlturaErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlAlturaErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtAlturaFocusLost

    private void jtLarguraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtLarguraFocusLost
        // TODO add your handling code here:
        if (jtLargura.getText().isEmpty()) {
            jtLargura.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtLargura.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtLargura.getText().isEmpty()){
            jlLarguraErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlLarguraErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtLarguraFocusLost

    private void jtComprimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtComprimentoFocusLost
        // TODO add your handling code here:
        if (jtComprimento.getText().isEmpty()) {
            jtComprimento.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtComprimento.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtComprimento.getText().isEmpty()){
            jlComprimentoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlComprimentoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtComprimentoFocusLost

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlAltura;
    private javax.swing.JLabel jlAlturaErro;
    private javax.swing.JLabel jlComprimento;
    private javax.swing.JLabel jlComprimentoErro;
    private javax.swing.JLabel jlLargura;
    private javax.swing.JLabel jlLarguraErro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JLabel jlPrecoErro;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JLabel jlQuantidadeErro;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JRadioButton jrCozinha;
    private javax.swing.JRadioButton jrQuarto;
    private javax.swing.JRadioButton jrSala;
    private javax.swing.JTextField jtAltura;
    private javax.swing.JTextField jtComprimento;
    private javax.swing.JTextField jtLargura;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPreco;
    private javax.swing.JTextField jtQuantidade;
    // End of variables declaration//GEN-END:variables
}
