/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Cliente;
import servicos.ClienteServicos;

/**
 *
 * @author vinicius
 */
public class UICadCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form UICadCliente
     */
    public UICadCliente() {
        initComponents();
    }
    Cliente cVO = new Cliente();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlpDados = new javax.swing.JLayeredPane();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlRg = new javax.swing.JLabel();
        jtRg = new javax.swing.JTextField();
        jlCpf = new javax.swing.JLabel();
        jtCpf = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jlEmail = new javax.swing.JLabel();
        jtTelefone = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        jlEndereco = new javax.swing.JLabel();
        jtEndereco = new javax.swing.JTextField();
        jlNomeErro = new javax.swing.JLabel();
        jlRgErro = new javax.swing.JLabel();
        jlCpfErro = new javax.swing.JLabel();
        jlTelefoneErro = new javax.swing.JLabel();
        jlEmailErro = new javax.swing.JLabel();
        jlEnderecoErro = new javax.swing.JLabel();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbCadastrar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastrar Clientes");

        jlpDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNome.setText("Nome");

        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtNomeFocusLost(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });

        jlRg.setText("Rg");

        jtRg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtRgFocusLost(evt);
            }
        });
        jtRg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtRgKeyPressed(evt);
            }
        });

        jlCpf.setText("Cpf");

        jtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtCpfFocusLost(evt);
            }
        });
        jtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCpfKeyPressed(evt);
            }
        });

        jlTelefone.setText("Telefone");

        jlEmail.setText("Email");

        jtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTelefoneFocusLost(evt);
            }
        });
        jtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTelefoneKeyPressed(evt);
            }
        });

        jtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtEmailFocusLost(evt);
            }
        });
        jtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtEmailKeyPressed(evt);
            }
        });

        jlEndereco.setText("Endereco");

        jtEndereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtEnderecoFocusLost(evt);
            }
        });
        jtEndereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtEnderecoKeyPressed(evt);
            }
        });

        jlpDados.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlRg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtRg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jtEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlNomeErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlRgErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlCpfErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlTelefoneErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlEmailErro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpDados.setLayer(jlEnderecoErro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpDadosLayout = new javax.swing.GroupLayout(jlpDados);
        jlpDados.setLayout(jlpDadosLayout);
        jlpDadosLayout.setHorizontalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlRg)
                    .addComponent(jlNome)
                    .addComponent(jlCpf)
                    .addComponent(jlEmail)
                    .addComponent(jlTelefone)
                    .addComponent(jlEndereco))
                .addGap(46, 46, 46)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtTelefone)
                    .addComponent(jtEmail)
                    .addComponent(jtEndereco)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtRg)
                    .addComponent(jtCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlRgErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlCpfErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlTelefoneErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlEmailErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlEnderecoErro, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jlNomeErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jlpDadosLayout.setVerticalGroup(
            jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpDadosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlNome)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlNomeErro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlRgErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlRg)
                        .addComponent(jtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCpfErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlCpf)
                        .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTelefone)
                            .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpDadosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlTelefoneErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlEmail))
                    .addComponent(jlEmailErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlEndereco))
                    .addComponent(jlEnderecoErro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbCadastrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpDados)
                    .addComponent(jlpAcoes))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlpDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlpAcoes)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrar(){
        try {
            if (!jtNome.getText().isEmpty()) {
               cVO.setNome(jtNome.getText());
            } else {
                throw new NumberFormatException("Nome em Branco!");
            }
            if (!jtRg.getText().isEmpty()) {
               cVO.setRg(jtRg.getText());
            } else {
                throw new NumberFormatException("Rg em Branco!");
            }
            if (!jtCpf.getText().isEmpty()) {
               cVO.setCpf(jtCpf.getText());
            } else {
                throw new NumberFormatException("Cpf em Branco!");
            }
            if (!jtEmail.getText().isEmpty()) {
                cVO.setEmail(jtEmail.getText());
            } else {
                throw new NumberFormatException("Email em Branco! ");
            }
            if (!jtTelefone.getText().isEmpty()) {
                cVO.setTelefone(Integer.parseInt(jtTelefone.getText()));
            } else {
                throw new NumberFormatException("Telefone em Branco! ");
            }
            if (!jtEndereco.getText().isEmpty()) {
                cVO.setEndereco(jtEndereco.getText());
            } else {
                throw new NumberFormatException("Endereço em Branco! ");
            }
            
            ClienteServicos cs = servicos.ServicosFactory.getClienteServicos();
            
            cs.cadastrarCliente(cVO);
            
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Cliente cadastrado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    rootPane, 
                    "Erro! " + e.getMessage(),
                    "erro",
                    JOptionPane.ERROR_MESSAGE);
        }//fecha catch
    }//fecha método
    
    public void limpar(){
        jtNome.setText("");
        jtRg.setText("");
        jtCpf.setText("");
        jtTelefone.setText("");
        jtEndereco.setText("");
        jtEmail.setText("");
        jtNome.grabFocus();
    }
    
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtRg.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtRgKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtRgKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCpf.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtRgKeyPressed

    private void jtCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCpfKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtTelefone.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtCpfKeyPressed

    private void jtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTelefoneKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtEmail.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtTelefoneKeyPressed

    private void jtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEmailKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtEndereco.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtEmailKeyPressed

    private void jtEnderecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEnderecoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbCadastrar.grabFocus();
        }//fecha if
    }//GEN-LAST:event_jtEnderecoKeyPressed

    private void jtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusLost
        // TODO add your handling code here:
        if (jtNome.getText().isEmpty()) {
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtNome.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtNome.getText().isEmpty()){
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlNomeErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtNomeFocusLost

    private void jtRgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtRgFocusLost
        // TODO add your handling code here:
        if (jtRg.getText().isEmpty()) {
            jtRg.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtRg.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtRg.getText().isEmpty()){
            jlRgErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlRgErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtRgFocusLost

    private void jtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtCpfFocusLost
        // TODO add your handling code here:
        if (jtNome.getText().isEmpty()) {
            jtNome.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtCpf.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtCpf.getText().isEmpty()){
            jlCpfErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlCpfErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtCpfFocusLost

    private void jtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTelefoneFocusLost
        // TODO add your handling code here:
        if (jtTelefone.getText().isEmpty()) {
            jtTelefone.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtTelefone.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtTelefone.getText().isEmpty()){
            jlTelefoneErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlTelefoneErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtTelefoneFocusLost

    private void jtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEmailFocusLost
        // TODO add your handling code here:
        if (jtEmail.getText().isEmpty()) {
            jtEmail.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtEmail.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtEmail.getText().isEmpty()){
            jlEmailErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlEmailErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtEmailFocusLost

    private void jtEnderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtEnderecoFocusLost
        // TODO add your handling code here:
        if (jtEndereco.getText().isEmpty()) {
            jtEndereco.setBorder(BorderFactory.createLineBorder(Color.red));
        }else{
            jtEndereco.setBorder(BorderFactory.createLineBorder(Color.blue));
        }
        if(jtEndereco.getText().isEmpty()){
            jlEnderecoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/error.png")));
        }else{
            jlEnderecoErro.setIcon(new ImageIcon(getClass().getResource("/imagens/ok.png")));
        }
    }//GEN-LAST:event_jtEnderecoFocusLost


    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlCpfErro;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlEmailErro;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlEnderecoErro;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNomeErro;
    private javax.swing.JLabel jlRg;
    private javax.swing.JLabel jlRgErro;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLabel jlTelefoneErro;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpDados;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtEndereco;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtRg;
    private javax.swing.JTextField jtTelefone;
    // End of variables declaration//GEN-END:variables
}
