/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import modelo.Movel;
import servicos.MovelServicos;
import servicos.ServicosFactory;

/**
 *
 * @author vinicius
 */
public class UIManutencaoMovel extends javax.swing.JInternalFrame {

    /**
     * Creates new form UIManutencaoMoveis
     */
     DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código","Nome","Preço", "Tipo", "Quantidade", "Altura", "Largura", "Comprimento"});
    public UIManutencaoMovel() {
        initComponents();
        preencherTabela();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipo = new javax.swing.ButtonGroup();
        jlpGeral = new javax.swing.JLayeredPane();
        jbPesquisar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbConfirmarAlteracao = new javax.swing.JButton();
        jlpFiltrar = new javax.swing.JLayeredPane();
        jtPesq = new javax.swing.JTextField();
        jcomboFiltro = new javax.swing.JComboBox<>();
        jlpTabela = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableMoveis = new javax.swing.JTable();
        jlpAlterar = new javax.swing.JLayeredPane();
        jlCodigo = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jlPreco = new javax.swing.JLabel();
        jtPreco = new javax.swing.JTextField();
        jlTipo = new javax.swing.JLabel();
        jrQuarto = new javax.swing.JRadioButton();
        jrSala = new javax.swing.JRadioButton();
        jrCozinha = new javax.swing.JRadioButton();
        jlQuantidade = new javax.swing.JLabel();
        jtQuantidade = new javax.swing.JTextField();
        jlAltura = new javax.swing.JLabel();
        jtAltura = new javax.swing.JTextField();
        jlLargura = new javax.swing.JLabel();
        jtLargura = new javax.swing.JTextField();
        jlComprimento = new javax.swing.JLabel();
        jtComprimento = new javax.swing.JTextField();
        jbAlterar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manutenção de Moveis");

        jlpGeral.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbPesquisar.setText("Preencher");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbConfirmarAlteracao.setText("Confirmar Alteração");
        jbConfirmarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarAlteracaoActionPerformed(evt);
            }
        });

        jlpGeral.setLayer(jbPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpGeral.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpGeral.setLayer(jbExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpGeral.setLayer(jbConfirmarAlteracao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpGeralLayout = new javax.swing.GroupLayout(jlpGeral);
        jlpGeral.setLayout(jlpGeralLayout);
        jlpGeralLayout.setHorizontalGroup(
            jlpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpGeralLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbConfirmarAlteracao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpGeralLayout.setVerticalGroup(
            jlpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbConfirmarAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jlpGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlpFiltrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesqKeyReleased(evt);
            }
        });

        jcomboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Código", "Preço", "Tipo", "Quantidade", "Altura", "Largura", "Comprimento" }));

        jlpFiltrar.setLayer(jtPesq, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpFiltrar.setLayer(jcomboFiltro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpFiltrarLayout = new javax.swing.GroupLayout(jlpFiltrar);
        jlpFiltrar.setLayout(jlpFiltrarLayout);
        jlpFiltrarLayout.setHorizontalGroup(
            jlpFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpFiltrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jcomboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jlpFiltrarLayout.setVerticalGroup(
            jlpFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpFiltrarLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jlpFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jlpTabela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtableMoveis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtableMoveis.getTableHeader().setReorderingAllowed(false);
        jtableMoveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMoveisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableMoveis);

        jlpTabela.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpTabelaLayout = new javax.swing.GroupLayout(jlpTabela);
        jlpTabela.setLayout(jlpTabelaLayout);
        jlpTabelaLayout.setHorizontalGroup(
            jlpTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jlpTabelaLayout.setVerticalGroup(
            jlpTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpTabelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlpAlterar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlCodigo.setText("Código");

        jtCodigo.setEditable(false);

        jlNome.setText("Nome");

        jlPreco.setText("Preço");

        jlTipo.setText("Tipo");

        bgTipo.add(jrQuarto);
        jrQuarto.setText("Quarto");
        jrQuarto.setActionCommand("Vendas");

        bgTipo.add(jrSala);
        jrSala.setText("Sala");
        jrSala.setActionCommand("Montagem");

        bgTipo.add(jrCozinha);
        jrCozinha.setText("Cozinha");
        jrCozinha.setActionCommand("Marketing");

        jlQuantidade.setText("Quantidade");

        jlAltura.setText("Altura");

        jlLargura.setText("Largura");

        jlComprimento.setText("Comprimento");

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jlpAlterar.setLayer(jlCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlTipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrQuarto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrSala, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrCozinha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlQuantidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtQuantidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlAltura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtAltura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlLargura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtLargura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlComprimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtComprimento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jbAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAlterarLayout = new javax.swing.GroupLayout(jlpAlterar);
        jlpAlterar.setLayout(jlpAlterarLayout);
        jlpAlterarLayout.setHorizontalGroup(
            jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAlterarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCodigo)
                    .addComponent(jlNome)
                    .addComponent(jlPreco)
                    .addComponent(jlTipo)
                    .addComponent(jlQuantidade)
                    .addComponent(jlAltura)
                    .addComponent(jlLargura)
                    .addComponent(jlComprimento))
                .addGap(34, 34, 34)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpAlterarLayout.createSequentialGroup()
                        .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtCodigo)
                            .addComponent(jtNome)
                            .addComponent(jtPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpAlterarLayout.createSequentialGroup()
                        .addComponent(jrQuarto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrCozinha))
                    .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAlterarLayout.setVerticalGroup(
            jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAlterarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlCodigo)
                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTipo)
                    .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrQuarto)
                        .addComponent(jrSala)
                        .addComponent(jrCozinha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQuantidade)
                    .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAltura)
                    .addComponent(jtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlLargura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlComprimento))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpFiltrar)
            .addComponent(jlpTabela)
            .addComponent(jlpGeral)
            .addComponent(jlpAlterar)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jlpFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlpGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void preencherTabela() {
        try {   
            MovelServicos ms = ServicosFactory.getMovelServicos();
            ArrayList<Movel> mov = new ArrayList<>();
            mov = ms.buscarMovel();

            for (int i = 0; i < mov.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(mov.get(i).getIdMovel()),
                    String.valueOf(mov.get(i).getNome()),
                    String.valueOf(mov.get(i).getPreco()),
                    String.valueOf(mov.get(i).getTipo()),
                    String.valueOf(mov.get(i).getQuantidade()),
                    String.valueOf(mov.get(i).getAltura()),
                    String.valueOf(mov.get(i).getLargura()),
                    String.valueOf(mov.get(i).getComprimento())
                });
            }
            jtableMoveis.setModel(dtm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }
    }
    private void limparTabela(){
        dtm.setNumRows(0);
    }
    private void filtrar(){
        try {
            if(jtPesq.getText().isEmpty()){
                preencherTabela();
            }else{
                MovelServicos ms = ServicosFactory.getMovelServicos();
                String pesquisa = (String) jcomboFiltro.getSelectedItem();
                String query;
                if (pesquisa.equals("Código")){
                    query = "where idMovel = "+jtPesq.getText();
                }else if(pesquisa.equals("Nome")){
                    query = "where nome like '%" + jtPesq.getText()+"%'";
                }else if (pesquisa.equals("Preço")){
                    query = "where preco like '%"+jtPesq.getText()+"%'";
                }else if(pesquisa.equals("Tipo")){
                    query = "where tipo like '%"+jtPesq.getText()+"%'";
                }else if(pesquisa.equals("Quantidade")){
                    query = "where tipo quantidade '%"+jtPesq.getText()+"%'";
                }else if(pesquisa.equals("Altura")){
                    query = "where altura like '%"+jtPesq.getText()+"%'";
                }else if(pesquisa.equals("Largura")){
                    query = "where largura like '%"+jtPesq.getText()+"%'";
                }else{
                    query = "where comprimento = "+jtPesq.getText();
                }
                ArrayList<Movel> mov = new ArrayList<>();
                mov = ms.filtrar(query);
                for(int i = 0; i<mov.size(); i++){
                    dtm.addRow(new String[]{
                    String.valueOf(mov.get(i).getIdMovel()),
                    String.valueOf(mov.get(i).getNome()),
                    String.valueOf(mov.get(i).getPreco()),
                    String.valueOf(mov.get(i).getTipo()),
                    String.valueOf(mov.get(i).getQuantidade()),
                    String.valueOf(mov.get(i).getAltura()),
                    String.valueOf(mov.get(i).getLargura()),
                    String.valueOf(mov.get(i).getComprimento())
                    });
                }
                jtableMoveis.setModel(dtm);
            
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Erro ao Filtrar! "+ e.getMessage());
        }
    }
    private void deletar(){
                try {
            int linha = jtableMoveis.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(
                        this,
                        "Você não selecionou nenhuma linha!");
            } else {
                MovelServicos ms = ServicosFactory.getMovelServicos();
                String idMovel = (String) jtableMoveis.getValueAt(linha, 0);
                ms.deletarMovel(Long.parseLong(idMovel));

                //Mensagem de sucesso para o usuário!
                JOptionPane.showMessageDialog(this,
                        "Produto excluido com sucesso!");

            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao deletar! " + e.getMessage());
        }//fecha catch       
    }
    
     private void alterar(){
        int linha = jtableMoveis.getSelectedRow();
        if(linha != -1){
            /* Buscando valores da linha selecionada na tabela como Objeto e 
               transformando os mesmos para String */
            jtCodigo.setText((String)jtableMoveis.getValueAt(linha, 0));
            jtNome.setText((String)jtableMoveis.getValueAt(linha, 1));
            jtQuantidade.setText((String)jtableMoveis.getValueAt(linha, 4));
            jtPreco.setText((String)jtableMoveis.getValueAt(linha, 2));
            jtAltura.setText((String)jtableMoveis.getValueAt(linha, 5));
            jtLargura.setText((String)jtableMoveis.getValueAt(linha, 6));
            jtComprimento.setText((String)jtableMoveis.getValueAt(linha, 7));
            
            String tipo = jtableMoveis.getValueAt(linha, 3).toString();
            
            if (tipo.equalsIgnoreCase("Quarto")) {
                jrQuarto.setSelected(true);
            } else if (tipo.equalsIgnoreCase("Sala")) {
                jrSala.setSelected(true);
            } else {
                jrCozinha.setSelected(true);
            }
            
        }else{
            JOptionPane.showMessageDialog(this, 
              "Você não selecionou nenhuma linha!");
        }//fecha else
    }//fecha método

    private void confirmarAlteracao(){
        try {
            Movel m = new Movel();
            //Buscando dados alterados pelo usuário nos JTextFields
            m.setIdMovel(Long.parseLong(jtCodigo.getText()));
            m.setNome(jtNome.getText());
            m.setPreco(Double.parseDouble(jtPreco.getText()));
            m.setAltura(Double.parseDouble(jtAltura.getText()));
            m.setLargura(Double.parseDouble(jtLargura.getText()));
            m.setComprimento(Double.parseDouble(jtComprimento.getText()));
            m.setQuantidade(Integer.parseInt(jtQuantidade.getText()));
            m.setTipo(bgTipo.getSelection().getActionCommand());
            
            MovelServicos ms = ServicosFactory.getMovelServicos();
            
            //Enviando o objeto para ser alterado
            ms.alterarMovel(m);
                        
            JOptionPane.showMessageDialog(
                    this, 
                    "Móvel Alterado com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! "+e.getMessage());
        }//fecha catch
    }//fecha método confirmarAlteração
    
    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparTabela();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        deletar();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqKeyReleased
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jtPesqKeyReleased

    private void jtableMoveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMoveisMouseClicked
        //jtableMoveis.setAutoCreateRowSorter(true);

    }//GEN-LAST:event_jtableMoveisMouseClicked

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        alterar();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbConfirmarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarAlteracaoActionPerformed
        // TODO add your handling code here:
        confirmarAlteracao();
    }//GEN-LAST:event_jbConfirmarAlteracaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConfirmarAlteracao;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JComboBox<String> jcomboFiltro;
    private javax.swing.JLabel jlAltura;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlComprimento;
    private javax.swing.JLabel jlLargura;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLayeredPane jlpAlterar;
    private javax.swing.JLayeredPane jlpFiltrar;
    private javax.swing.JLayeredPane jlpGeral;
    private javax.swing.JLayeredPane jlpTabela;
    private javax.swing.JRadioButton jrCozinha;
    private javax.swing.JRadioButton jrQuarto;
    private javax.swing.JRadioButton jrSala;
    private javax.swing.JTextField jtAltura;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtComprimento;
    private javax.swing.JTextField jtLargura;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPesq;
    private javax.swing.JTextField jtPreco;
    private javax.swing.JTextField jtQuantidade;
    private javax.swing.JTable jtableMoveis;
    // End of variables declaration//GEN-END:variables
}
