/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import modelo.Funcionario;
import servicos.FuncionarioServicos;
import servicos.ServicosFactory;

/**
 *
 * @author vinicius
 */
public class UIManutencaoFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form UIManutencaoFuncionario
     */
         DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Código","Nome","Cpf", "Rg", "Setor", "Telefone", "Endereço"});
    public UIManutencaoFuncionario() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSetor = new javax.swing.ButtonGroup();
        jlpFiltrar = new javax.swing.JLayeredPane();
        jtPesq = new javax.swing.JTextField();
        jcomboFiltrar = new javax.swing.JComboBox<>();
        jlpTabela = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlpAcoes = new javax.swing.JLayeredPane();
        jbPreencher = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbConfirmarAlteracao = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jlpAlterar = new javax.swing.JLayeredPane();
        jlCodigo = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlCpf = new javax.swing.JLabel();
        jlRg = new javax.swing.JLabel();
        jlSetor = new javax.swing.JLabel();
        jlTelefone = new javax.swing.JLabel();
        jlEndereco = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jtNome = new javax.swing.JTextField();
        jtCpf = new javax.swing.JTextField();
        jtRg = new javax.swing.JTextField();
        jtTelefone = new javax.swing.JTextField();
        jtEndereco = new javax.swing.JTextField();
        jrVendas = new javax.swing.JRadioButton();
        jrMontagem = new javax.swing.JRadioButton();
        jrMarketing = new javax.swing.JRadioButton();
        jbAlterar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Manutenção de Funcionario");

        jlpFiltrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesqKeyReleased(evt);
            }
        });

        jcomboFiltrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Código", "Cpf", "Rg", "Setor", "Telefone", "Endereço" }));

        jlpFiltrar.setLayer(jtPesq, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpFiltrar.setLayer(jcomboFiltrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpFiltrarLayout = new javax.swing.GroupLayout(jlpFiltrar);
        jlpFiltrar.setLayout(jlpFiltrarLayout);
        jlpFiltrarLayout.setHorizontalGroup(
            jlpFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpFiltrarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jcomboFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpFiltrarLayout.setVerticalGroup(
            jlpFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpFiltrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpFiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomboFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlpTabela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jlpTabela.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpTabelaLayout = new javax.swing.GroupLayout(jlpTabela);
        jlpTabela.setLayout(jlpTabelaLayout);
        jlpTabelaLayout.setHorizontalGroup(
            jlpTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jlpTabelaLayout.setVerticalGroup(
            jlpTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpTabelaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlpAcoes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbPreencher.setText("Preencher");
        jbPreencher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPreencherActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbConfirmarAlteracao.setText("Confirmar Alteração");
        jbConfirmarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarAlteracaoActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jlpAcoes.setLayer(jbPreencher, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbConfirmarAlteracao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAcoes.setLayer(jbExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAcoesLayout = new javax.swing.GroupLayout(jlpAcoes);
        jlpAcoes.setLayout(jlpAcoesLayout);
        jlpAcoesLayout.setHorizontalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jbPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbConfirmarAlteracao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAcoesLayout.setVerticalGroup(
            jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpAcoesLayout.createSequentialGroup()
                        .addGroup(jlpAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbPreencher, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jbConfirmarAlteracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jlpAlterar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlCodigo.setText("Código");

        jlNome.setText("Nome");

        jlCpf.setText("Cpf");

        jlRg.setText("Rg");

        jlSetor.setText("Setor");

        jlTelefone.setText("Telefone");

        jlEndereco.setText("Endereco");

        jtCodigo.setEditable(false);
        jtCodigo.setEnabled(false);

        bgSetor.add(jrVendas);
        jrVendas.setText("Vendas");
        jrVendas.setActionCommand("Vendas");

        bgSetor.add(jrMontagem);
        jrMontagem.setText("Montagem");
        jrMontagem.setActionCommand("Montagem");

        bgSetor.add(jrMarketing);
        jrMarketing.setText("Marketing");
        jrMarketing.setActionCommand("Marketing");

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jlpAlterar.setLayer(jlCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlRg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlSetor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jlEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtRg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtTelefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jtEndereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrVendas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrMontagem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jrMarketing, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpAlterar.setLayer(jbAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jlpAlterarLayout = new javax.swing.GroupLayout(jlpAlterar);
        jlpAlterar.setLayout(jlpAlterarLayout);
        jlpAlterarLayout.setHorizontalGroup(
            jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAlterarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCodigo)
                    .addComponent(jlNome)
                    .addComponent(jlCpf)
                    .addComponent(jlRg)
                    .addComponent(jlSetor)
                    .addComponent(jlTelefone)
                    .addComponent(jlEndereco))
                .addGap(31, 31, 31)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtCodigo)
                        .addComponent(jtNome)
                        .addComponent(jtCpf)
                        .addComponent(jtRg)
                        .addComponent(jtTelefone)
                        .addComponent(jtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                    .addGroup(jlpAlterarLayout.createSequentialGroup()
                        .addComponent(jrVendas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrMontagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrMarketing)))
                .addGap(61, 61, 61)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jlpAlterarLayout.setVerticalGroup(
            jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpAlterarLayout.createSequentialGroup()
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpAlterarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlCodigo))
                    .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNome)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCpf)
                    .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlRg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrMontagem)
                    .addComponent(jrVendas)
                    .addComponent(jrMarketing)
                    .addComponent(jlSetor))
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jlpAlterarLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jlTelefone))
                    .addGroup(jlpAlterarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEndereco))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpFiltrar)
            .addComponent(jlpTabela)
            .addComponent(jlpAlterar)
            .addComponent(jlpAcoes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlpFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void preencherTabela() {
        try {   
            FuncionarioServicos fs = ServicosFactory.getFuncionarioServicos();
            ArrayList<Funcionario> fun = new ArrayList<>();
            fun = fs.buscarFuncionario();

            for (int i = 0; i < fun.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(fun.get(i).getIdFuncionario()),
                    String.valueOf(fun.get(i).getNome()),
                    String.valueOf(fun.get(i).getCpf()),
                    String.valueOf(fun.get(i).getRg()),
                    String.valueOf(fun.get(i).getSetor()),
                    String.valueOf(fun.get(i).getTelefone()),
                    String.valueOf(fun.get(i).getEndereco())
                    
                });
            }
            jTable1.setModel(dtm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }
    }
    private void limparTabela(){
        dtm.setNumRows(0);
    }
    private void filtrar(){
        try {
            if(jtPesq.getText().isEmpty()){
                preencherTabela();
            }else{
                FuncionarioServicos fs = ServicosFactory.getFuncionarioServicos();
                String preencher = (String) jcomboFiltrar.getSelectedItem();
                String query;
                if (preencher.equals("Código")){
                    query = "where idFuncionario = "+jtPesq.getText();
                }else if(preencher.equals("Nome")){
                    query = "where nome like '%" + jtPesq.getText()+"%'";
                }else if (preencher.equals("Cpf")){
                    query = "where cpf like '%"+jtPesq.getText()+"%'";
                }else if(preencher.equals("Rg")){
                    query = "where rg like '%"+jtPesq.getText()+"%'";
                }else if(preencher.equals("Setor")){
                    query = "where setor like '%"+jtPesq.getText()+"%'";
                }else if(preencher.equals("Telefone")){
                    query = "where telefone like '%"+jtPesq.getText()+"%'";
                }else{
                    query = "where endereco = "+jtPesq.getText();
                }
                ArrayList<Funcionario> fun = new ArrayList<>();
                fun = fs.filtrar(query);
                for(int i = 0; i<fun.size(); i++){
                    dtm.addRow(new String[]{
                        String.valueOf(fun.get(i).getIdFuncionario()),
                    String.valueOf(fun.get(i).getNome()),
                    String.valueOf(fun.get(i).getCpf()),
                    String.valueOf(fun.get(i).getRg()),
                    String.valueOf(fun.get(i).getSetor()),
                    String.valueOf(fun.get(i).getTelefone()),
                    String.valueOf(fun.get(i).getEndereco())
                        
                    });
                }
                jTable1.setModel(dtm);
            
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Erro ao Filtrar! "+ e.getMessage());
        }
    }
    private void deletar() {
        try {
            int linha = jTable1.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(
                        this,
                        "Você não selecionou nenhuma linha!");
            } else {
                FuncionarioServicos ms = ServicosFactory.getFuncionarioServicos();
                String idFuncionario = (String) jTable1.getValueAt(linha, 0);
                ms.deletarFuncionario(Long.parseLong(idFuncionario));

                //Mensagem de sucesso para o usuário!
                JOptionPane.showMessageDialog(this,
                        "Produto excluido com sucesso!");

            }//fecha else
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao deletar! " + e.getMessage());
        }//fecha catch       
    }//fecha deletar
    
    private void alterar(){
        int linha = jTable1.getSelectedRow();
        if(linha != -1){
            /* Buscando valores da linha selecionada na tabela como Objeto e 
               transformando os mesmos para String */
            jtCodigo.setText((String)jTable1.getValueAt(linha, 0));
            jtNome.setText((String)jTable1.getValueAt(linha, 1));
            jtCpf.setText((String)jTable1.getValueAt(linha, 2));
            jtRg.setText((String)jTable1.getValueAt(linha, 3));
            
            String setor = jTable1.getValueAt(linha, 4).toString();
            
            if (setor.equalsIgnoreCase("Vendas")) {
                jrVendas.setSelected(true);
            } else if (setor.equalsIgnoreCase("Montagem")) {
                jrMontagem.setSelected(true);
            } else {
                jrMarketing.setSelected(true);
            }
            
            jtTelefone.setText((String)jTable1.getValueAt(linha, 5));
            jtEndereco.setText((String)jTable1.getValueAt(linha, 6));
        }else{
            JOptionPane.showMessageDialog(this, 
              "Você não selecionou nenhuma linha!");
        }//fecha else
    }//fecha método
    
    private void confirmarAlteracao(){
        try {
            Funcionario f = new Funcionario();
            //Buscando dados alterados pelo usuário nos JTextFields
            f.setIdFuncionario(Long.parseLong(jtCodigo.getText()));
            f.setNome(jtNome.getText());
            f.setCpf(jtCpf.getText());
            f.setRg(jtRg.getText());
            f.setEndereco(jtEndereco.getText());
            f.setTelefone(Integer.parseInt(jtTelefone.getText()));
            f.setSetor(bgSetor.getSelection().getActionCommand());
            
            FuncionarioServicos fs = ServicosFactory.getFuncionarioServicos();
            
            //Enviando o objeto para ser alterado
            fs.alterarFuncionario(f);
                        
            JOptionPane.showMessageDialog(
                    this, 
                    "Funcionario Alterado com sucesso!");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! "+e.getMessage());
        }//fecha catch
    }//fecha método confirmarAlteração
    
    private void jbPreencherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPreencherActionPerformed
        // TODO add your handling code here:
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbPreencherActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparTabela();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        deletar();
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqKeyReleased
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jtPesqKeyReleased

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        alterar();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbConfirmarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarAlteracaoActionPerformed
        // TODO add your handling code here:
        confirmarAlteracao();
    }//GEN-LAST:event_jbConfirmarAlteracaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSetor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbConfirmarAlteracao;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbPreencher;
    private javax.swing.JComboBox<String> jcomboFiltrar;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlCpf;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlRg;
    private javax.swing.JLabel jlSetor;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLayeredPane jlpAcoes;
    private javax.swing.JLayeredPane jlpAlterar;
    private javax.swing.JLayeredPane jlpFiltrar;
    private javax.swing.JLayeredPane jlpTabela;
    private javax.swing.JRadioButton jrMarketing;
    private javax.swing.JRadioButton jrMontagem;
    private javax.swing.JRadioButton jrVendas;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JTextField jtEndereco;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPesq;
    private javax.swing.JTextField jtRg;
    private javax.swing.JTextField jtTelefone;
    // End of variables declaration//GEN-END:variables
}
